services:
  wordpress:
    build: .
    container_name: "plugintest_wp_local"
    ports:
      - "8082:80"  # WordPress
    volumes:
      - ./../acf-image-size-select:/var/www/html/wp-content/plugins/acf-image-size-select
      - ./../menu-duplicator:/var/www/html/wp-content/plugins/menu-duplicator
      - ./../query-monitor-image-sizes:/var/www/html/wp-content/plugins/query-monitor-image-sizes
      - ./wordpress:/var/www/html  # Optional: Allow WP-CLI commands
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WP_ENVIRONMENT_TYPE: local       # Set environment type to 'local'
      WORDPRESS_DEBUG: 1                 # Enable WP_DEBUG
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', '/var/www/html/debug.log' );
        define( 'SCRIPT_DEBUG', true );
        @ini_set( 'log_errors', 'On' );
        @ini_set( 'error_log', '/var/www/html/debug.log' );
    networks:
      - "plugintest_network"

  db:
    image: mariadb:10.11.9
    container_name: "plugintest_wp_db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - "plugintest_db_data:/var/lib/mysql"
    networks:
      - "plugintest_network"

  adminer:
    image: adminer:latest
    container_name: "plugintest_adminer"
    ports:
      - "8083:8080"  # Adminer interface
    networks:
      - "plugintest_network"

networks:
  "plugintest_network": {}

volumes:
  "plugintest_db_data": {}
